baseURL = "https://lifeandbites.com/"
languageCode = "en-us"
summaryLength = 30
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "Blog"
url = "/blog"
weight = 2
[[menu.main]]
name = "Contact"
url = "/contact"
weight = 5
[taxonomies]
category = "categories"
tag = "tags"
recipe = "recipes"