baseURL = "https://lifeandbites.com/"
languageCode = "en-us"
summaryLength = 20
[params]
cloudinary_url = "https://res.cloudinary.com/hungryram19/image/upload"
[[menu.main]]
name = "Food Favorites"
url = "/favorites"
weight = 4
[[menu.main]]
name = "Life"
url = "/categories/life"
weight = 2
[[menu.main]]
name = "Shop"
url = "/shop"
weight = 5
[[menu.main]]
name = "Recipes"
url = "/recipes"
weight = 3
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "Contact"
url = "/contact"
weight = 6
[taxonomies]
category = "categories"
recipe = "recipes"
tag = "tags"
