baseURL = "https://lifeandbites.com/"
languageCode = "en-us"
summaryLength = 20
[[menu.main]]
name = "Shop"
url = "/shop"
weight = 5
[[menu.main]]
name = "Recipes"
url = "/recipes"
weight = 4
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "Blog"
url = "/blog"
weight = 2
[[menu.main]]
name = "Contact"
url = "/contact"
weight = 6
[taxonomies]
category = "categories"
recipe = "recipes"
tag = "tags"
