---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin"
webhook_url: 
sections:
- type: document
  path: data/profile.yaml
  label: Profile
- type: document
  path: data/design.yaml
  label: Design
- type: document
  path: data/home.yaml
  label: Home Content
- type: directory
  path: content/author
  label: Author
  create: documents
  match: "**/*"
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: document
  path: content/shop/_index.md
  label: Shop
- type: document
  path: content/favorites/_index.md
  label: Favorite Foods
- type: document
  path: content/contact/_index.md
  label: Contact
- type: heading
  label: Blog
- type: directory
  path: content/blog
  label: Posts
  create: documents
  match: "**/*"
  templates:
  - blog
- type: directory
  path: content/recipes
  label: Recipes
  create: documents
  match: "**/*"
  templates:
  - recipes
- type: heading
  label: Legal
- type: document
  path: content/legal/privacy-policy.md
  label: Privacy Policy
- type: document
  path: content/legal/accessibility.md
  label: Accessibility
- type: document
  path: content/legal/terms-and-conditions.md
  label: Terms and Conditions
upload_dir: lifeandbites
public_path: https://res.cloudinary.com/hungryram19/image/upload
front_matter_path: ''
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.71.1
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.71.1
